services:
  # Backend Service
  - type: web
    name: trafictrack-backend
    env: docker
    plan: free
    rootDir: backend
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: APP_ENC_KEY
        value: /O57NYDzbL6ML5Hinm/PrHEFjPjOSl9yxaQQ87rZ42k=
      - key: PORT
        value: 8081

  # Frontend Service
  - type: web
    name: trafictrack-frontend
    runtime: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l 3000
    envVars:
      - key: REACT_APP_API_URL
        value: https://trafictrack-backend.onrender.com
