services: 
  - type: web 
    name: trafictrack-prod 
    runtime: java
    plan: starter 
    buildCommand: mvn -f backend/pom.xml clean package 
    startCommand: java -jar backend/target/trafic-track-backend-0.0.1-SNAPSHOT.jar 
    envVars: 
      - key: APP_ENC_KEY 
        value: /O57NYDzbL6ML5Hinm/PrHEFjPjOSl9yxaQQ87rZ42k=
